import os
FILE = "C:/Users/Akshit/Desktop/AnimalKingdom/Animal_kingdom_01___Basis_of_Classification.mp4"
FILE_NAME = "Animal_kingdom_01___Basis_of_Classification.mp4"
SIZE = 10000000

file = open(FILE, "rb")
file_stats = os.stat(FILE)

size = file_stats.st_size
data = file.read()


access_token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Ikx2X1NEVmNTS1ItZEozeU5pTTZXb2lfc0xZTjhzMTltVktzMV90RV8zaWciLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83YWQ5ZDc1OC1hNjY0LTQ0YWUtYjZkNy04MmVhYjFiYTk2MGQvIiwiaWF0IjoxNzE4MDA5NzAzLCJuYmYiOjE3MTgwMDk3MDMsImV4cCI6MTcxODAxNDU3MCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhXQUFBQUxsWXZYdzQ0c2hYMmxnMDhtQUFDVGZUZnltemFkMVRXZlJwWGROaW5QaUMxcFRzZUQ1NE9xVWpUaFNpUmY2clZ0RXVtRGNMSlZnTTBKeE5oZGwxMU1YUW5vRk1yN1JoTkFlcW1naXQrUHZ3PSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoib25lRHJpdmVfdXAiLCJhcHBpZCI6Ijk1N2NjNTBlLTFiZGMtNDVmMi04MmUxLThmYjY2YmQ5OTE2NiIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiU2h1YmhhbSIsImdpdmVuX25hbWUiOiJBa3NoaXQiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyNDA5OjQwZTU6MTc6MjgwYTo2MGY0OmJkNzk6MTRiZjozZWRiIiwibmFtZSI6IkFrc2hpdCBTaHViaGFtIiwib2lkIjoiYWZjYmU4ZDktN2NiMS00ZGFjLWI0MzgtMjdiNjhkZTc2NDZkIiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDAyOEZDMDdFMUYiLCJyaCI6IjAuQVZJQVdOZlplbVNtcmtTMjE0THFzYnFXRFFNQUFBQUFBQUFBd0FBQUFBQUFBQUM2QUlNLiIsInNjcCI6IkZpbGVzLlJlYWRXcml0ZSBGaWxlcy5SZWFkV3JpdGUuQWxsIEZpbGVzLlJlYWRXcml0ZS5BcHBGb2xkZXIgRmlsZXMuUmVhZFdyaXRlLlNlbGVjdGVkIG9wZW5pZCBwcm9maWxlIFNpdGVzLkZ1bGxDb250cm9sLkFsbCBTaXRlcy5NYW5hZ2UuQWxsIFNpdGVzLlJlYWQuQWxsIFNpdGVzLlJlYWRXcml0ZS5BbGwgU2l0ZXMuU2VsZWN0ZWQgVXNlci5FeHBvcnQuQWxsIFVzZXIuUmVhZCBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6ImhsZ2VWekJ1THBGazFQRnBxdHNjbXVMUDV2aTctdXRFY0hmWklSTGZVZWsiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiI3YWQ5ZDc1OC1hNjY0LTQ0YWUtYjZkNy04MmVhYjFiYTk2MGQiLCJ1bmlxdWVfbmFtZSI6ImFrc2hpdEAxNDcxYmwub25taWNyb3NvZnQuY29tIiwidXBuIjoiYWtzaGl0QDE0NzFibC5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiJYclk0TVNyYnZFeW1xcUN0bU5LeEFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3N0Ijp7InN1YiI6IktGUTA5eGJYNG9ZRk9wMGkxMmcwZjFOeGRhTG5tUGpEQU5tSXJhdXNzT2cifSwieG1zX3RjZHQiOjE2ODAzMzYyMDF9.mLqyzAD6kQz0BIv0ALk2y34ac2YV8JC6xMgotjDf0_yegYpVvdfIvOKBLNzuvIhJ9T-LDc7NObgg1lwQCjvVSwVxvpZMpOJrTNUU-2lYQpoQC8wJJFt4b73k1aww3LcyojJKHa9PJcff-vgUA6MZA_OUuxQpHEPezhx_gh7nKfjVOUvpOXfqyuoJTVGW4EuWLni54pWcvXpr5Fn0pDAuX4BQC8TOCYfIvs5xIOpYqvcMBiwPOYEQ9FErkBroO0tNceFADpu1PU9uaFqZJvj5EF0rmvK5d7MsTuHhWqdNuCgLCfZMu8_uuBIlU-MXmzwoSmIkCWXyC2a_ixwx_S_PCA"



from main import createUploadSession
from main import uploadBytesToUploadSession
response = createUploadSession(access_token, FILE_NAME)
print(response)

url = response['uploadUrl']

length = size

count = 1


while True:
    start = SIZE * (count-1)
    end = SIZE * count
    print(f"Start: {start} End: {end}")
    if end > length:
        end = length

    response_json = uploadBytesToUploadSession(access_token,url,start,data[start:end],length)
    print(response_json)
    if end == length:
        break

    count += 1